version: "3"
services:
  postgres:
    image: "postgres:latest"
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - "3000:80"
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /app/node_modules
      - ./server:/app
    environment: # all default values from postgres image from docker hub
      - PGUSER=${PG_USER}
      - PGHOST=${PG_HOST}
      - PGDATABASE=${PG_DB}
      - PGPASSWORD=${PG_PASS}
      - PGPORT=${PG_PORT}
  client:
    stdin_open: true
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
