export const UPDATE_CITY = "UPDATE_CITY";
export const UPDATE_BUTTON_STATE = "UPDATE_BUTTON_STATE";
export const UPDATE_CITY_RATINGS = "UPDATE_CITY_RATINGS ";
export const UPDATE_CITY_SALARIES = "UPDATE_CITY_SALARIES ";
